language: python
sudo: false
python:
    - "2.7"
    - "3.3"
    - "3.4"
addons:
  apt:
    packages:
     - zip
install: 
    - pip install -r requirements.txt
    - python setup.py install
script:  bash clam/tests/test.sh
